import PageIntro from "@/components/PageIntro";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ArrowRight, BarChart3, CalendarDays, CircleAlert, Recycle, Sprout } from "lucide-react";
import { Bar, BarChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Link } from "wouter";

const labels: Record<string, string> = { reciclavel: "Reciclável", organico: "Orgânico", rejeito: "Rejeito", eletronico: "Eletrônico", perigoso: "Perigoso" };

export default function Dashboard() {
  const { data, isLoading } = trpc.dashboard.resumo.useQuery();
  const metrics = [
    { label: "Total coletado", value: data?.totalKg ? `${data.totalKg.toLocaleString("pt-BR")} kg` : "—", helper: data?.completedCount ? `${data.completedCount} coleta(s) concluída(s)` : "Aguardando registros", icon: Recycle, tone: "emerald" },
    { label: "Taxa de reciclagem", value: data?.recyclingRate === null || data?.recyclingRate === undefined ? "—" : `${data.recyclingRate}%`, helper: data?.recyclingRate === null ? "Disponível após as coletas" : "Sobre o material coletado", icon: Sprout, tone: "sage" },
    { label: "Coletas concluídas", value: data?.completedCount ? `${data.completedCount}` : "—", helper: data?.completedCount ? "No período atual" : "Nenhuma coleta finalizada", icon: CalendarDays, tone: "blue" },
    { label: "Ocorrências", value: data?.occurrenceCount ? `${data.occurrenceCount}` : "—", helper: data?.occurrenceCount ? "Registros que pedem atenção" : "Sem dados para exibir", icon: CircleAlert, tone: "orange" },
  ];
  const tones = { emerald: "bg-[#e5f6ec] text-[#0a7048]", sage: "bg-[#edf4dc] text-[#637b20]", blue: "bg-[#e8f1fb] text-[#2863a5]", orange: "bg-[#fff0e7] text-[#b45522]" };
  const chartData = (data?.byWasteType ?? []).map((item: { wasteType: string; kilograms: number }) => ({ name: labels[item.wasteType] ?? item.wasteType, kg: item.kilograms }));
  const hasData = chartData.some((item) => item.kg > 0);

  return <div>
    <PageIntro eyebrow="Painel operacional" title="A sustentabilidade começa com uma operação clara." description="Acompanhe os indicadores de coleta, o engajamento dos moradores e as atividades que precisam de atenção." action={<Button asChild className="h-10 rounded-xl bg-[#0f7350] px-4 font-semibold text-white hover:bg-[#0a6243]"><Link href="/coletas">Registrar coleta <ArrowRight className="ml-2 h-4 w-4" /></Link></Button>} />
    <section aria-label="Indicadores da operação" className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map((metric) => { const Icon = metric.icon; return <article key={metric.label} className="rounded-[22px] border border-[#dce8e0] bg-white p-5 shadow-[0_16px_34px_-28px_rgba(4,66,42,.42)]"><div className="flex items-start justify-between gap-3"><p className="text-sm font-medium text-muted-foreground">{metric.label}</p><span className={`grid h-9 w-9 place-items-center rounded-xl ${tones[metric.tone as keyof typeof tones]}`}><Icon className="h-[18px] w-[18px]" /></span></div><p className="mt-6 text-[30px] font-bold tracking-[-0.05em] text-foreground">{isLoading ? "…" : metric.value}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{metric.helper}</p></article>; })}</section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><article className="min-h-[345px] rounded-[24px] border border-[#dce8e0] bg-white p-5 shadow-[0_16px_34px_-28px_rgba(4,66,42,.35)] sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-base font-semibold tracking-[-0.025em]">Coleta por categoria</p><p className="mt-1 text-sm text-muted-foreground">Material concluído e registrado no período atual.</p></div><Badge variant="outline" className="border-[#dce8e0] bg-[#f8fbf9] text-xs font-medium text-muted-foreground">Dados ao vivo</Badge></div>{hasData ? <div className="mt-5 h-[240px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={chartData} margin={{ top: 12, right: 5, left: -24, bottom: 0 }}><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fontSize: 11, fill: "#6b7e74" }} /><YAxis axisLine={false} tickLine={false} tick={{ fontSize: 11, fill: "#6b7e74" }} /><Tooltip cursor={{ fill: "#edf7f1" }} contentStyle={{ borderRadius: 14, border: "1px solid #dce8e0", fontSize: 12 }} formatter={(value) => [`${value} kg`, "Volume"]} /><Bar dataKey="kg" fill="#0f7350" radius={[8, 8, 2, 2]} /></BarChart></ResponsiveContainer></div> : <div className="mt-8 grid h-[215px] place-items-center rounded-2xl border border-dashed border-[#cfe1d7] bg-[#fbfdfc] px-6 text-center"><div><span className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-[#e8f4ed] text-[#0f7350]"><BarChart3 className="h-5 w-5" /></span><p className="mt-4 text-sm font-semibold">Os gráficos aparecerão aqui.</p><p className="mt-1 max-w-sm text-xs leading-5 text-muted-foreground">Registre a primeira coleta concluída para iniciar a leitura do desempenho ambiental do condomínio.</p></div></div>}</article><article className="rounded-[24px] border border-[#dce8e0] bg-[linear-gradient(145deg,#0d5c43,#0b382b)] p-6 text-white shadow-[0_18px_40px_-24px_rgba(4,66,42,.65)]"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-white/12"><Sprout className="h-5 w-5" /></span><p className="mt-6 text-[11px] font-bold tracking-[0.14em] text-[#bfe7cf] uppercase">Próximo passo</p><h2 className="mt-2 text-xl font-bold tracking-[-0.04em]">Estruture a primeira coleta.</h2><p className="mt-3 text-sm leading-6 text-[#d7ece0]">Defina tipo de resíduo, bloco, data, horário e responsável. Ao concluir, o EcoCondo atualiza os indicadores e a pontuação.</p><Button asChild variant="secondary" className="mt-7 h-10 rounded-xl border-0 bg-white px-4 text-sm font-semibold text-[#0b533a] hover:bg-[#e8f4ed]"><Link href="/coletas">Ir para coletas <ArrowRight className="ml-2 h-4 w-4" /></Link></Button></article></section>
    <section className="mt-5 rounded-[24px] border border-[#dce8e0] bg-white p-5 shadow-[0_16px_34px_-28px_rgba(4,66,42,.32)] sm:p-6"><div className="flex items-center justify-between"><div><p className="text-base font-semibold tracking-[-0.025em]">Atividades recentes</p><p className="mt-1 text-sm text-muted-foreground">Últimas coletas registradas na sua área de acesso.</p></div><Link href="/coletas" className="text-sm font-semibold text-[#0f7350] hover:underline">Ver histórico</Link></div>{data?.recent?.length ? <div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-5">{data.recent.map((record) => <article key={record.id} className="rounded-2xl border border-[#e1ebe5] bg-[#fbfdfc] p-4"><div className="flex items-center justify-between"><Badge className="border-0 bg-[#edf7f1] text-[10px] font-bold tracking-[.06em] text-[#0a7048] hover:bg-[#edf7f1]">{labels[record.tipoResiduo]}</Badge><span className="text-[11px] text-muted-foreground">{record.status}</span></div><p className="mt-4 text-sm font-semibold">Bloco {record.bloco}</p><p className="mt-1 text-xs text-muted-foreground">{new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(record.agendadaPara)}</p></article>)}</div> : <p className="mt-5 rounded-2xl bg-[#f8fbf9] p-4 text-sm text-muted-foreground">As atividades recentes aparecerão aqui assim que as coletas forem registradas.</p>}</section>
  </div>;
}
