import PageIntro from "@/components/PageIntro";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { Bell, Check, MessageSquarePlus, Plus } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

export default function Notifications() {
  const utils = trpc.useUtils();
  const profile = trpc.profile.me.useQuery();
  const { data: items, isLoading } = trpc.notifications.list.useQuery();
  const unread = trpc.notifications.unreadCount.useQuery();
  const refreshNotifications = () => { utils.notifications.list.invalidate(); utils.notifications.unreadCount.invalidate(); };
  const markRead = trpc.notifications.markRead.useMutation({ onSuccess: refreshNotifications });
  const markAllRead = trpc.notifications.markAllRead.useMutation({ onSuccess: () => { refreshNotifications(); toast.success("Suas notificações foram marcadas como lidas."); } });
  const createCommunication = trpc.notifications.createCommunication.useMutation({ onSuccess: () => { refreshNotifications(); toast.success("Comunicado publicado."); setTitle(""); setMessage(""); setIsFormOpen(false); }, onError: (issue) => toast.error(issue.message) });
  const [isFormOpen, setIsFormOpen] = useState(false); const [title, setTitle] = useState(""); const [message, setMessage] = useState("");
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); createCommunication.mutate({ title, message }); }
  const isAdmin = profile.data?.role === "administrador";
  const notificationAction = <div className="flex gap-2"><Button variant="outline" disabled={!unread.data?.count || markAllRead.isPending} onClick={() => markAllRead.mutate()} className="h-10 rounded-xl bg-white text-xs">Marcar minhas como lidas</Button>{isAdmin && <Button onClick={() => setIsFormOpen((open) => !open)} className="h-10 rounded-xl bg-[#0f7350] font-semibold text-white hover:bg-[#0a6243]"><MessageSquarePlus className="mr-2 h-4 w-4" />Novo comunicado</Button>}</div>;
  return <div><PageIntro eyebrow="Comunicação" title="Notificações" description={`${unread.data?.count ?? 0} notificação(ões) não lida(s) para você. A leitura é individual e não afeta os demais usuários.`} action={notificationAction} /><section className="rounded-[24px] border border-[#dce8e0] bg-white p-5 shadow-[0_16px_34px_-28px_rgba(4,66,42,.35)] sm:p-6">{isFormOpen && <form onSubmit={submit} className="mb-5 grid gap-3 rounded-2xl border border-[#cfe1d7] bg-[#f7fbf8] p-4"><label className="grid gap-1.5 text-xs font-semibold">Título<Input required value={title} onChange={(event) => setTitle(event.target.value)} className="h-10 rounded-xl bg-white" /></label><label className="grid gap-1.5 text-xs font-semibold">Mensagem<textarea required value={message} onChange={(event) => setMessage(event.target.value)} className="min-h-24 rounded-xl border border-[#dce8e0] bg-white p-3 text-sm outline-none focus:ring-2 focus:ring-[#0f7350]/30" /></label><div className="flex gap-2"><Button disabled={createCommunication.isPending} className="h-10 rounded-xl bg-[#0f7350] text-white hover:bg-[#0a6243]">Publicar comunicado</Button><Button type="button" variant="ghost" onClick={() => setIsFormOpen(false)} className="h-10 rounded-xl">Cancelar</Button></div></form>}{isLoading ? <p className="py-12 text-center text-sm text-muted-foreground">Carregando notificações...</p> : !items?.length ? <div className="grid min-h-64 place-items-center text-center"><div><span className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-[#e8f4ed] text-[#0f7350]"><Bell className="h-5 w-5" /></span><p className="mt-4 text-sm font-semibold">Tudo em dia.</p><p className="mt-1 text-xs text-muted-foreground">As notificações operacionais e comunicados aparecerão aqui.</p></div></div> : <div className="divide-y divide-[#edf2ef]">{items.map((item) => <article key={item.id} className={`flex gap-4 py-4 ${item.readAt ? "opacity-65" : ""}`}><span className={`mt-0.5 grid h-10 w-10 shrink-0 place-items-center rounded-xl ${item.kind === "comunicado" ? "bg-[#e9f1fb] text-[#2863a5]" : "bg-[#e8f4ed] text-[#0f7350]"}`}><Bell className="h-[18px] w-[18px]" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-sm font-semibold">{item.title}</p><span className="text-[11px] text-muted-foreground">{new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(item.createdAt)}</span></div><p className="mt-1 text-sm leading-6 text-muted-foreground">{item.message}</p></div>{!item.readAt && <Button size="icon" variant="ghost" onClick={() => markRead.mutate({ id: item.id })} className="h-8 w-8 rounded-lg text-[#0f7350] hover:bg-[#edf7f1]" aria-label="Marcar como lida"><Check className="h-4 w-4" /></Button>}</article>)}</div>}</section></div>;
}
