import PageIntro from "@/components/PageIntro";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { ShieldCheck, UserRoundPlus, UsersRound } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { Link } from "wouter";
import { toast } from "sonner";

type PersonRole = "administrador" | "coletor" | "morador";

export default function Settings() {
  const utils = trpc.useUtils();
  const condominium = trpc.condominium.current.useQuery();
  const directory = trpc.people.directory.useQuery();
  const updateCondominium = trpc.condominium.update.useMutation({ onSuccess: () => { utils.condominium.current.invalidate(); utils.profile.me.invalidate(); toast.success("Dados do condomínio atualizados."); }, onError: (issue) => toast.error(issue.message) });
  const setRole = trpc.people.setRole.useMutation({ onSuccess: () => { utils.people.directory.invalidate(); toast.success("Perfil atualizado."); }, onError: (issue) => toast.error(issue.message) });
  const [form, setForm] = useState({ name: "", address: "", city: "", state: "", blockCount: 1 });
  useEffect(() => { if (condominium.data) setForm({ name: condominium.data.name, address: condominium.data.address || "", city: condominium.data.city || "", state: condominium.data.state || "", blockCount: condominium.data.blockCount }); }, [condominium.data]);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); updateCondominium.mutate({ ...form, address: form.address || null, city: form.city || null, state: form.state ? form.state.toUpperCase() : null }); }
  return <div>
    <PageIntro eyebrow="Administração" title="Configurações" description="Ajuste o condomínio e acompanhe pessoas, acessos pendentes e perfis de responsabilidade." />
    <div className="grid gap-5 xl:grid-cols-[.8fr_1.2fr]">
      <section className="rounded-[24px] border border-[#dce8e0] bg-white p-5 shadow-[0_16px_34px_-28px_rgba(4,66,42,.35)] sm:p-6"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#e8f4ed] text-[#0f7350]"><ShieldCheck className="h-5 w-5" /></span><div><p className="font-semibold">Dados do condomínio</p><p className="text-sm text-muted-foreground">Informações visíveis nos relatórios.</p></div></div><form onSubmit={submit} className="mt-5 grid gap-3"><label className="grid gap-1.5 text-xs font-semibold">Nome<Input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} className="h-10 rounded-xl bg-[#fbfdfc]" /></label><label className="grid gap-1.5 text-xs font-semibold">Endereço<Input value={form.address} onChange={(event) => setForm({ ...form, address: event.target.value })} className="h-10 rounded-xl bg-[#fbfdfc]" /></label><div className="grid grid-cols-[1fr_70px] gap-3"><label className="grid gap-1.5 text-xs font-semibold">Cidade<Input value={form.city} onChange={(event) => setForm({ ...form, city: event.target.value })} className="h-10 rounded-xl bg-[#fbfdfc]" /></label><label className="grid gap-1.5 text-xs font-semibold">UF<Input maxLength={2} value={form.state} onChange={(event) => setForm({ ...form, state: event.target.value })} className="h-10 rounded-xl bg-[#fbfdfc]" /></label></div><label className="grid gap-1.5 text-xs font-semibold">Quantidade de blocos<Input required type="number" min="1" max="99" value={form.blockCount} onChange={(event) => setForm({ ...form, blockCount: Number(event.target.value) })} className="h-10 rounded-xl bg-[#fbfdfc]" /></label><Button disabled={updateCondominium.isPending} className="mt-2 h-10 rounded-xl bg-[#0f7350] text-white hover:bg-[#0a6243]">Salvar configurações</Button></form></section>
      <section className="rounded-[24px] border border-[#dce8e0] bg-white p-5 shadow-[0_16px_34px_-28px_rgba(4,66,42,.35)] sm:p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#e8f4ed] text-[#0f7350]"><UsersRound className="h-5 w-5" /></span><div><p className="font-semibold">Perfis de acesso</p><p className="text-sm text-muted-foreground">Cadastre a pessoa uma vez e defina sua responsabilidade antes do primeiro login.</p></div></div><Link href="/pessoas" className="inline-flex h-9 items-center justify-center rounded-xl bg-[#0f7350] px-3 text-xs font-semibold text-white hover:bg-[#0a6243]"><UserRoundPlus className="mr-1.5 h-3.5 w-3.5" />Cadastrar pessoa</Link></div>{directory.isLoading ? <p className="mt-6 text-sm text-muted-foreground">Carregando acessos...</p> : !directory.data?.length ? <p className="mt-6 text-sm text-muted-foreground">Nenhuma pessoa foi cadastrada ainda. Use o botão acima para adicionar moradores, coletores ou administradores.</p> : <div className="mt-5 divide-y divide-[#edf2ef]">{directory.data.map(({ person, user, resident }) => <article key={person.id} className="flex flex-col gap-3 py-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold">{person.name}</p><p className="mt-0.5 text-xs text-muted-foreground">{person.email}{resident ? ` · ${resident.block} · ${resident.apartment}` : ""}</p></div><div className="flex flex-wrap items-center gap-2"><Badge className={person.accessStatus === "ativo" ? "border-0 bg-[#e7f5ec] text-[#0a7048]" : "border-0 bg-[#fff4dd] text-[#996312]"}>{person.accessStatus === "ativo" ? "Acesso ativo" : "Aguardando login"}</Badge><select value={person.role} onChange={(event) => setRole.mutate({ id: person.id, role: event.target.value as PersonRole })} disabled={setRole.isPending} className="h-9 rounded-lg border border-[#dce8e0] bg-white px-2 text-xs font-semibold"><option value="administrador">Administrador</option><option value="coletor">Coletor</option><option value="morador">Morador</option></select>{user && <span className="text-xs font-medium text-[#0a7048]">Vinculado</span>}</div></article>)}</div>}</section>
    </div>
  </div>;
}
